CO_Oxidation=['O2','O','CO','CO2']
CO2_Reduction=['CO2','H2','H','COOH','HCOO']
C2H4_Epoxidation=['C2H4','CH2CH2O','O','C2H2','H']
C2H2_Hydrogenation=['C2H2','C2H3','C2H4','H2','H']
C3H8_Dehydrogenation=['C3H8','C3H6','H2','H2','H']
AmmoniaSynthesis=['NH3','N','H','NH','NH2','NNH']
ORR_OER=['OOH','OH','H2O','O','O2']
HER_HOR=['OH','H2O','H','H2']
CO2_Electroreduction=['CO2','CO','H2O','H','O']
NOx_Oxidation=['NO','NO2','NO3','N','O']
CH4_Activation=['CH4','C','H','CH3','CH2','CH']
Fischer_Tropsch=['CO','O','H','HCO','COH','CH2']
Waterinterface=['H2O','H2O','H2O','H2O']
type3=[
        {'name': 'Ru', 'mp_id': 'mp-33', 'ads': AmmoniaSynthesis},
        {'name': 'Ru', 'mp_id': 'mp-33', 'ads': Waterinterface},
        {'name': 'Rh', 'mp_id': 'mp-74', 'ads': AmmoniaSynthesis},
        {'name': 'Rh', 'mp_id': 'mp-74', 'ads': CO2_Reduction},
        {'name': 'Rh', 'mp_id': 'mp-74', 'ads': CH4_Activation},
        {'name': 'Ag', 'mp_id': 'mp-124', 'ads': C2H4_Epoxidation},
        {'name': 'Ag', 'mp_id': 'mp-124', 'ads': CO_Oxidation},
        {'name': 'Ag', 'mp_id': 'mp-124', 'ads': ORR_OER},
        {'name': 'Ag', 'mp_id': 'mp-124', 'ads': Waterinterface},
        {'name': 'Pt', 'mp_id': 'mp-126', 'ads': NOx_Oxidation},
        {'name': 'Pt', 'mp_id': 'mp-126', 'ads': Waterinterface},
        {'name': 'Pt', 'mp_id': 'mp-126', 'ads': HER_HOR},
        {'name': 'Pt', 'mp_id': 'mp-126', 'ads': AmmoniaSynthesis},
        {'name': 'Pt', 'mp_id': 'mp-126', 'ads': C3H8_Dehydrogenation},
        {'name': 'Pt', 'mp_id': 'mp-126', 'ads': CO2_Reduction},
        {'name': 'Cu', 'mp_id': 'mp-30', 'ads': CO_Oxidation},
        {'name': 'Cu', 'mp_id': 'mp-30', 'ads': CO2_Reduction},
        {'name': 'Cu', 'mp_id': 'mp-30', 'ads': CO2_Electroreduction},
        {'name': 'Cu', 'mp_id': 'mp-30', 'ads': ORR_OER},
        {'name': 'Cu', 'mp_id': 'mp-30', 'ads': CH4_Activation},
        {'name': 'Cu', 'mp_id': 'mp-30', 'ads': Fischer_Tropsch},
        {'name': 'Cu', 'mp_id': 'mp-30', 'ads': Waterinterface},
        {'name': 'Au', 'mp_id': 'mp-81', 'ads': CO_Oxidation},
        {'name': 'Au', 'mp_id': 'mp-81', 'ads': Waterinterface},
        {'name': 'Fe', 'mp_id': 'mp-13', 'ads': AmmoniaSynthesis},
        {'name': 'Fe', 'mp_id': 'mp-13', 'ads': Fischer_Tropsch},
        {'name': 'Co', 'mp_id': 'mp-54', 'ads': AmmoniaSynthesis},
        {'name': 'Co', 'mp_id': 'mp-54', 'ads': Fischer_Tropsch},
        {'name': 'Ni', 'mp_id': 'mp-23', 'ads': CO2_Reduction},
        {'name': 'Ni', 'mp_id': 'mp-23', 'ads': CH4_Activation},
        {'name': 'Pd', 'mp_id': 'mp-2', 'ads': C2H2_Hydrogenation},
        {'name': 'Pd', 'mp_id': 'mp-2', 'ads': ORR_OER},
        {'name': 'Pd', 'mp_id': 'mp-2', 'ads': HER_HOR},
        {'name': 'Pd', 'mp_id': 'mp-2', 'ads': Waterinterface},
        {'name': 'Ir', 'mp_id': 'mp-101', 'ads': CO2_Reduction},
        {'name': 'Ir', 'mp_id': 'mp-101', 'ads': CH4_Activation},
        {'name': 'Ir', 'mp_id': 'mp-101', 'ads': Waterinterface},
        {'name': 'Zn', 'mp_id': 'mp-79', 'ads': CO2_Reduction},
        ]

alloy_element_list = [
       "Fe",
       "Co",
       "Ni",
       "Cu",
       "Zn",
       "Ru",
       "Rh",
       "Pd",
       "Ag",
       "Ir",
       "Pt",
       "Au",
       "Ti",
       "V",
       "Cr",
       "Mn",
       "Y",
       "Zr",
       "Nb",
       "Mo",
       "Li",
       "Na",
       "K",
       "Rb",
       "Be",
       "Mg",
       "Ca",
       "Sc",
       "Cd",
       "Hf",
       "Ta",
       "W",
       "Re",
       "Os",
       "Al",
       "Ga",
       "In",
       "Ge",
       "Sn",
       "Pb",
       "Sb",
       "Bi",
]

metal_element_list = [
       "Fe",
       "Co",
       "Ni",
       "Cu",
       "Zn",
       "Ru",
       "Rh",
       "Pd",
       "Ag",
       "Ir",
       "Pt",
       "Au",
       "Ti",
       "V",
       "Cr",
       "Mn",
       "Y",
       "Zr",
       "Nb",
       "Mo",
       "Li",
       "Na",
       "K",
       "Rb",
       "Cs",
       "Be",
       "Mg",
       "Ca",
       "Sr",
       "Ba",
       "Sc",
       "Cd",
       "Hf",
       "Ta",
       "W",
       "Re",
       "Os",
       "Al",
       "Ga",
       "In",
       "Ge",
       "Sn",
       "Pb",
       "Sb",
       "Bi",
       "Ce",
]

type1=[ 
	{'name': 'Li', 'mp_id': 'mp-135', 'ads': ['H', 'C', 'O', 'S', 'CO', 'H2', 'O2', 'H2O', 'CO2']},
	{'name': 'Na', 'mp_id': 'mp-127', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'H2O']},
	{'name': 'Mg', 'mp_id': 'mp-153', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'N2', 'H2O', 'CO2', 'NH3']},
        {'name': 'Fe', 'mp_id': 'mp-13', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'H2O', 'CO2', 'CH4', 'HCHO', 'OH', 'OOH', 'CH', 'CH2', 'CH3', 'HCO', 'COH', 'HCOH', 'H2CO', 'CH3O', 'H2COH']},
        {'name': 'Co', 'mp_id': 'mp-54', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'NO', 'H2O', 'CO2', 'CH4', 'OH', 'OOH', 'CH', 'CH2', 'CH3', 'HCO', 'COH', 'HCOH', 'H2CO', 'H2COH']},
        {'name': 'Ni', 'mp_id': 'mp-23', 'ads': ['H', 'C', 'O', 'N', 'S', 'CO', 'H2', 'O2', 'H2O', 'CO2', 'CH4', 'C2H2', 'C2H4', 'CH', 'CH2', 'CH3', 'HCO', 'COH', 'HCOH', 'H2CO', 'H2COH']},
        {'name': 'Cu', 'mp_id': 'mp-30', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'NO', 'H2O', 'CO2', 'CH4', 'CH3OH', 'HCOOH', 'C2H2', 'C2H4', 'C2H6', 'CH3CH2OH', 'CH3COOH', 'OH', 'OOH', 'CN', 'HCO', 'COH', 'HCOH', 'H2CO', 'COOH', 'HCOO', 'CH3O', 'H2COH']},
        {'name': 'Zn', 'mp_id': 'mp-79', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'H2O', 'CO2', 'CH4', 'CH3OH', 'OH', 'CH3', 'HCO', 'COH', 'HCOH', 'H2CO', 'COOH', 'HCOO', 'CH3O', 'H2COH']},
        {'name': 'Ru', 'mp_id': 'mp-33', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'N2', 'NO', 'H2O', 'CO2', 'NH3', 'CH4', 'OH', 'OOH', 'NH', 'NH2', 'NNH', 'NO3']},
        {'name': 'Rh', 'mp_id': 'mp-74', 'ads': ['H', 'C', 'O', 'N', 'S', 'CO', 'H2', 'O2', 'N2', 'NO', 'N2O', 'H2O', 'CO2', 'NH3', 'CH4', 'HCO', 'COH', 'HCOH', 'H2CO', 'NH', 'NH2', 'NNH']},
        {'name': 'Pd', 'mp_id': 'mp-2', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'N2', 'NO', 'H2O', 'CO2', 'NH3', 'CH4', 'C2H2', 'C2H4', 'OH', 'HCO', 'COH', 'HCOH', 'H2CO', 'NH', 'NH2']},
        {'name': 'Ag', 'mp_id': 'mp-124', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'N2', 'NO', 'H2O', 'CO2', 'NH3', 'CH4', 'HCHO', 'C2H2', 'C2H4', 'NH', 'NH2', 'NNH', 'NO3']},
        {'name': 'Ir', 'mp_id': 'mp-101', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'N2', 'NO', 'H2O', 'CO2', 'NH3', 'CH4', 'CH3OH', 'OH', 'OOH', 'HCO', 'COH', 'HCOH', 'H2CO', 'H2COH']},
        {'name': 'Pt', 'mp_id': 'mp-126', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'N2', 'NO', 'H2O', 'CO2', 'NH3', 'CH4', 'CH3OH', 'C3H6', 'C3H8', 'OH', 'OOH', 'HCO', 'COH', 'HCOH', 'H2CO', 'H2COH']},
        {'name': 'Au', 'mp_id': 'mp-81', 'ads': ['H', 'C', 'O', 'N', 'CO', 'H2', 'O2', 'NO', 'H2O', 'CO2', 'NH3', 'CH4', 'C2H2', 'HCO', 'COH', 'HCOH', 'H2CO', 'H2COH', 'NO3']},
	{'name': 'Al', 'mp_id': 'mp-134', 'ads': ['H', 'C', 'O', 'CO', 'H2', 'O2', 'H2O']}
        ]
type2=[
	{'name': 'K', 'mp_id': 'mp-58'},
	{'name': 'Rb', 'mp_id': 'mp-70'},
	{'name': 'Cs', 'mp_id': 'mp-1'},
	{'name': 'Be', 'mp_id': 'mp-87'},
	{'name': 'Ca', 'mp_id': 'mp-45'},
	{'name': 'Sr', 'mp_id': 'mp-76'},
	{'name': 'Ba', 'mp_id': 'mp-122'},
	{'name': 'Sc', 'mp_id': 'mp-67'},
	{'name': 'V', 'mp_id': 'mp-146'},
	{'name': 'Y', 'mp_id': 'mp-112'},
	{'name': 'Nb', 'mp_id': 'mp-75'},
	{'name': 'Mo', 'mp_id': 'mp-129'},
	{'name': 'Cd', 'mp_id': 'mp-94'},
	{'name': 'Hf', 'mp_id': 'mp-103'},
        {'name': 'Ti', 'mp_id': 'mp-46'},
	{'name': 'Cr', 'mp_id': 'mp-90'},
	{'name': 'Mn', 'mp_id': 'mp-35'},
	{'name': 'Zr', 'mp_id': 'mp-131'},
	{'name': 'Ta', 'mp_id': 'mp-50'},
	{'name': 'W', 'mp_id': 'mp-91'},
	{'name': 'Re', 'mp_id': 'mp-8'},
	{'name': 'Os', 'mp_id': 'mp-49'},
	{'name': 'Ga', 'mp_id': 'mp-142'},
	{'name': 'In', 'mp_id': 'mp-1055994'},
	{'name': 'Ge', 'mp_id': 'mp-32'},
	{'name': 'Sn', 'mp_id': 'mp-117'},
	{'name': 'Pb', 'mp_id': 'mp-20483'},
	{'name': 'Sb', 'mp_id': 'mp-104'},
	{'name': 'Bi', 'mp_id': 'mp-23152'},
        {'name': 'Ce', 'mp_id': 'mp-28'},
        {'name': 'Ag3Au', 'mp_id': 'mp-1183137'},
        {'name': 'Au3Ag', 'mp_id': 'mp-985287'},
        {'name': 'Ni3Pt', 'mp_id': 'mp-12798'},
        {'name': 'Pt3Ni', 'mp_id': 'mp-1186117'},
        {'name': 'Cu3Pd', 'mp_id': 'mp-580357'},
        {'name': 'Pd3Au', 'mp_id': 'mp-999298'},
        {'name': 'Au3Pd', 'mp_id': 'mp-973834'},
        {'name': 'Ag3Pt', 'mp_id': 'mp-12065'},
        {'name': 'Pt3Ag', 'mp_id': 'mp-30353'},
        {'name': 'Cu3Pt', 'mp_id': 'mp-12086'},
        {'name': 'Ag3Ni', 'mp_id': 'mp-976772'},
        {'name': 'Au3Ni', 'mp_id': 'mp-976784'},
        {'name': 'Cu3Au', 'mp_id': 'mp-2258'},
        {'name': 'Au3Cu', 'mp_id': 'mp-2103'},
        {'name': 'Au3Co', 'mp_id': 'mp-1206590'},
        {'name': 'Pd3Zn', 'mp_id': 'mp-1187913'},
        {'name': 'Fe3Pt', 'mp_id': 'mp-1649'},
        {'name': 'Pt3Fe', 'mp_id': 'mp-649'},
        {'name': 'Pt3Sn', 'mp_id': 'mp-20971'},
        {'name': 'Pd3In', 'mp_id': 'mp-21215'},
        {'name': 'Pt3Co', 'mp_id': 'mp-922'},
        {'name': 'Ni3Ga', 'mp_id': 'mp-815'},
        {'name': 'Pt3Zn', 'mp_id': 'mp-30856'},
        {'name': 'Ag3Pd', 'mp_id': 'mp-985296'},
        {'name': 'FeCo', 'mp_id': 'mp-2090'},
        {'name': 'FeNi', 'mp_id': 'mp-2213'},
        {'name': 'FeZn', 'mp_id': 'mp-1207450'},
        {'name': 'FeRh', 'mp_id': 'mp-1918'},
        {'name': 'FePd', 'mp_id': 'mp-21845'},
        {'name': 'FeIr', 'mp_id': 'mp-1184336'},
        {'name': 'FePt', 'mp_id': 'mp-2260'},
        {'name': 'FeTi', 'mp_id': 'mp-305'},
        {'name': 'FeV', 'mp_id': 'mp-866134'},
        {'name': 'FeY', 'mp_id': 'mp-1102392'},
        {'name': 'FeZr', 'mp_id': 'mp-1718'},
        {'name': 'FeNb', 'mp_id': 'mp-1221111'},
        {'name': 'FeMo', 'mp_id': 'mp-1213182'},
        {'name': 'FeBe', 'mp_id': 'mp-2225'},
        {'name': 'FeSc', 'mp_id': 'mp-540'},
        {'name': 'FeHf', 'mp_id': 'mp-333'},
        {'name': 'FeTa', 'mp_id': 'mp-1218218'},
        {'name': 'FeW', 'mp_id': 'mp-20868'},
        {'name': 'FeRe', 'mp_id': 'mp-639789'},
        {'name': 'FeAl', 'mp_id': 'mp-2658'},
        {'name': 'FeGa', 'mp_id': 'mp-19870'},
        {'name': 'FeGe', 'mp_id': 'mp-20344'},
        {'name': 'FeSn', 'mp_id': 'mp-21260'},
        {'name': 'FeSb', 'mp_id': 'mp-20714'},
        {'name': 'FeCe', 'mp_id': 'mp-204'},
        {'name': 'CoNi', 'mp_id': 'mp-1183837'},
        {'name': 'CoZn', 'mp_id': 'mp-1192361'},
        {'name': 'CoPt', 'mp_id': 'mp-949'},
        {'name': 'CoTi', 'mp_id': 'mp-823'},
        {'name': 'CoV', 'mp_id': 'mp-1002109'},
        {'name': 'CoMn', 'mp_id': 'mp-1009133'},
        {'name': 'CoY', 'mp_id': 'mp-865373'},
        {'name': 'CoZr', 'mp_id': 'mp-2283'},
        {'name': 'CoNb', 'mp_id': 'mp-977426'},
        {'name': 'CoBe', 'mp_id': 'mp-2773'},
        {'name': 'CoSc', 'mp_id': 'mp-253'},
        {'name': 'CoHf', 'mp_id': 'mp-2027'},
        {'name': 'CoTa', 'mp_id': 'mp-11358'},
        {'name': 'CoRe', 'mp_id': 'mp-865960'},
        {'name': 'CoAl', 'mp_id': 'mp-284'},
        {'name': 'CoGa', 'mp_id': 'mp-1121'},
        {'name': 'CoIn', 'mp_id': 'mp-22236'},
        {'name': 'CoGe', 'mp_id': 'mp-21237'},
        {'name': 'CoSn', 'mp_id': 'mp-20536'},
        {'name': 'CoSb', 'mp_id': 'mp-1317'},
        {'name': 'CoCe', 'mp_id': 'mp-1112'},
        {'name': 'NiZn', 'mp_id': 'mp-429'},
        {'name': 'NiPt', 'mp_id': 'mp-945'},
        {'name': 'NiTi', 'mp_id': 'mp-1409'},
        {'name': 'NiV', 'mp_id': 'mp-7226'},
        {'name': 'NiMn', 'mp_id': 'mp-11500'},
        {'name': 'NiY', 'mp_id': 'mp-569196'},
        {'name': 'NiZr', 'mp_id': 'mp-485'},
        {'name': 'NiNb', 'mp_id': 'mp-1451'},
        {'name': 'NiMo', 'mp_id': 'mp-11506'},
        {'name': 'NiBe', 'mp_id': 'mp-1033'},
        {'name': 'NiMg', 'mp_id': 'mp-2137'},
        {'name': 'NiCa', 'mp_id': 'mp-2295'},
        {'name': 'NiSc', 'mp_id': 'mp-850'},
        {'name': 'NiHf', 'mp_id': 'mp-12174'},
        {'name': 'NiTa', 'mp_id': 'mp-569776'},
        {'name': 'NiW', 'mp_id': 'mp-30811'},
        {'name': 'NiRe', 'mp_id': 'mp-862604'},
        {'name': 'NiAl', 'mp_id': 'mp-2593'},
        {'name': 'NiIn', 'mp_id': 'mp-19876'},
        {'name': 'NiGe', 'mp_id': 'mp-21008'},
        {'name': 'NiSn', 'mp_id': 'mp-11522'},
        {'name': 'NiSb', 'mp_id': 'mp-810'},
        {'name': 'NiBi', 'mp_id': 'mp-999318'},
        {'name': 'NiCe', 'mp_id': 'mp-1654'},
        {'name': 'CuZn', 'mp_id': 'mp-987'},
        {'name': 'CuPd', 'mp_id': 'mp-1018029'},
        {'name': 'CuTi', 'mp_id': 'mp-1077023'},
        {'name': 'CuY', 'mp_id': 'mp-2698'},
        {'name': 'CuZr', 'mp_id': 'mp-193'},
        {'name': 'CuLi', 'mp_id': 'mp-862658'},
        {'name': 'CuBe', 'mp_id': 'mp-2031'},
        {'name': 'CuMg', 'mp_id': 'mp-2481'},
        {'name': 'CuCa', 'mp_id': 'mp-585949'},
        {'name': 'CuSr', 'mp_id': 'mp-2726'},
        {'name': 'CuBa', 'mp_id': 'mp-30428'},
        {'name': 'CuSc', 'mp_id': 'mp-1018149'},
        {'name': 'CuHf', 'mp_id': 'mp-30581'},
        {'name': 'CuAl', 'mp_id': 'mp-2500'},
        {'name': 'CuGa', 'mp_id': 'mp-865798'},
        {'name': 'CuIn', 'mp_id': 'mp-646039'},
        {'name': 'CuCe', 'mp_id': 'mp-2801'},
        {'name': 'ZnRu', 'mp_id': 'mp-1205290'},
        {'name': 'ZnRh', 'mp_id': 'mp-865342'},
        {'name': 'ZnPd', 'mp_id': 'mp-1215714'},
        {'name': 'ZnAg', 'mp_id': 'mp-1093999'},
        {'name': 'ZnIr', 'mp_id': 'mp-865362'},
        {'name': 'ZnPt', 'mp_id': 'mp-865355'},
        {'name': 'ZnAu', 'mp_id': 'mp-1684'},
        {'name': 'ZnTi', 'mp_id': 'mp-1014229'},
        {'name': 'ZnV', 'mp_id': 'mp-11578'},
        {'name': 'ZnMn', 'mp_id': 'mp-11504'},
        {'name': 'ZnY', 'mp_id': 'mp-2516'},
        {'name': 'ZnZr', 'mp_id': 'mp-864889'},
        {'name': 'ZnNb', 'mp_id': 'mp-953'},
        {'name': 'ZnMo', 'mp_id': 'mp-972048'},
        {'name': 'ZnLi', 'mp_id': 'mp-1934'},
        {'name': 'ZnNa', 'mp_id': 'mp-950'},
        {'name': 'ZnK', 'mp_id': 'mp-784'},
        {'name': 'ZnRb', 'mp_id': 'mp-2504'},
        {'name': 'ZnMg', 'mp_id': 'mp-1124'},
        {'name': 'ZnCa', 'mp_id': 'mp-30483'},
        {'name': 'ZnSr', 'mp_id': 'mp-12724'},
        {'name': 'ZnBa', 'mp_id': 'mp-1018178'},
        {'name': 'ZnSc', 'mp_id': 'mp-13503'},
        {'name': 'ZnHf', 'mp_id': 'mp-866108'},
        {'name': 'ZnTa', 'mp_id': 'mp-862679'},
        {'name': 'ZnSb', 'mp_id': 'mp-753'},
        {'name': 'ZnCe', 'mp_id': 'mp-1385'},
        {'name': 'RuRh', 'mp_id': 'mp-1186926'},
        {'name': 'RuIr', 'mp_id': 'mp-862620'},
        {'name': 'RuTi', 'mp_id': 'mp-592'},
        {'name': 'RuV', 'mp_id': 'mp-1395'},
        {'name': 'RuMn', 'mp_id': 'mp-865045'},
        {'name': 'RuY', 'mp_id': 'mp-1207781'},
        {'name': 'RuZr', 'mp_id': 'mp-214'},
        {'name': 'RuNb', 'mp_id': 'mp-977434'},
        {'name': 'RuMo', 'mp_id': 'mp-975834'},
        {'name': 'RuBe', 'mp_id': 'mp-1103315'},
        {'name': 'RuMg', 'mp_id': 'mp-625'},
        {'name': 'RuSc', 'mp_id': 'mp-30867'},
        {'name': 'RuHf', 'mp_id': 'mp-2802'},
        {'name': 'RuTa', 'mp_id': 'mp-977390'},
        {'name': 'RuW', 'mp_id': 'mp-862655'},
        {'name': 'RuRe', 'mp_id': 'mp-862630'},
        {'name': 'RuOs', 'mp_id': 'mp-1220023'},
        {'name': 'RuAl', 'mp_id': 'mp-16529'},
        {'name': 'RuGa', 'mp_id': 'mp-672204'},
        {'name': 'RuIn', 'mp_id': 'mp-607450'},
        {'name': 'RuGe', 'mp_id': 'mp-21945'},
        {'name': 'RuSn', 'mp_id': 'mp-680677'},
        {'name': 'RuSb', 'mp_id': 'mp-20928'},
        {'name': 'RuCe', 'mp_id': 'mp-607'},
        {'name': 'RhIr', 'mp_id': 'mp-1184794'},
        {'name': 'RhPt', 'mp_id': 'mp-974376'},
        {'name': 'RhTi', 'mp_id': 'mp-1018124'},
        {'name': 'RhV', 'mp_id': 'mp-971751'},
        {'name': 'RhCr', 'mp_id': 'mp-12585'},
        {'name': 'RhMn', 'mp_id': 'mp-417'},
        {'name': 'RhY', 'mp_id': 'mp-191'},
        {'name': 'RhZr', 'mp_id': 'mp-1188413'},
        {'name': 'RhNb', 'mp_id': 'mp-1963'},
        {'name': 'RhMo', 'mp_id': 'mp-12595'},
        {'name': 'RhLi', 'mp_id': 'mp-600561'},
        {'name': 'RhBe', 'mp_id': 'mp-11276'},
        {'name': 'RhMg', 'mp_id': 'mp-542429'},
        {'name': 'RhCa', 'mp_id': 'mp-1214063'},
        {'name': 'RhSr', 'mp_id': 'mp-1328'},
        {'name': 'RhBa', 'mp_id': 'mp-568430'},
        {'name': 'RhSc', 'mp_id': 'mp-1780'},
        {'name': 'RhHf', 'mp_id': 'mp-1190626'},
        {'name': 'RhTa', 'mp_id': 'mp-1103212'},
        {'name': 'RhW', 'mp_id': 'mp-30866'},
        {'name': 'RhRe', 'mp_id': 'mp-867865'},
        {'name': 'RhAl', 'mp_id': 'mp-364'},
        {'name': 'RhGa', 'mp_id': 'mp-2444'},
        {'name': 'RhIn', 'mp_id': 'mp-18614'},
        {'name': 'RhGe', 'mp_id': 'mp-22239'},
        {'name': 'RhSn', 'mp_id': 'mp-1103044'},
        {'name': 'RhPb', 'mp_id': 'mp-442'},
        {'name': 'RhSb', 'mp_id': 'mp-20619'},
        {'name': 'RhBi', 'mp_id': 'mp-23217'},
        {'name': 'RhCe', 'mp_id': 'mp-1018117'},
        {'name': 'PdAg', 'mp_id': 'mp-1229012'},
        {'name': 'PdPt', 'mp_id': 'mp-1219908'},
        {'name': 'PdTi', 'mp_id': 'mp-13164'},
        {'name': 'PdV', 'mp_id': 'mp-1664'},
        {'name': 'PdCr', 'mp_id': 'mp-865786'},
        {'name': 'PdMn', 'mp_id': 'mp-1102640'},
        {'name': 'PdY', 'mp_id': 'mp-1066136'},
        {'name': 'PdZr', 'mp_id': 'mp-266'},
        {'name': 'PdNb', 'mp_id': 'mp-1220678'},
        {'name': 'PdMo', 'mp_id': 'mp-1206704'},
        {'name': 'PdLi', 'mp_id': 'mp-728'},
        {'name': 'PdBe', 'mp_id': 'mp-13452'},
        {'name': 'PdMg', 'mp_id': 'mp-18712'},
        {'name': 'PdCa', 'mp_id': 'mp-1104669'},
        {'name': 'PdSr', 'mp_id': 'mp-999143'},
        {'name': 'PdBa', 'mp_id': 'mp-1064367'},
        {'name': 'PdSc', 'mp_id': 'mp-2781'},
        {'name': 'PdCd', 'mp_id': 'mp-1696'},
        {'name': 'PdHf', 'mp_id': 'mp-1007692'},
        {'name': 'PdTa', 'mp_id': 'mp-999133'},
        {'name': 'PdRe', 'mp_id': 'mp-862586'},
        {'name': 'PdAl', 'mp_id': 'mp-7189'},
        {'name': 'PdGa', 'mp_id': 'mp-1078526'},
        {'name': 'PdIn', 'mp_id': 'mp-22646'},
        {'name': 'PdGe', 'mp_id': 'mp-1424'},
        {'name': 'PdSn', 'mp_id': 'mp-2369'},
        {'name': 'PdPb', 'mp_id': 'mp-20599'},
        {'name': 'PdSb', 'mp_id': 'mp-1769'},
        {'name': 'PdBi', 'mp_id': 'mp-1008488'},
        {'name': 'PdCe', 'mp_id': 'mp-1018086'},
        {'name': 'AgPt', 'mp_id': 'mp-1183209'},
        {'name': 'AgTi', 'mp_id': 'mp-979115'},
        {'name': 'AgY', 'mp_id': 'mp-2474'},
        {'name': 'AgZr', 'mp_id': 'mp-2221'},
        {'name': 'AgLi', 'mp_id': 'mp-2426'},
        {'name': 'AgNa', 'mp_id': 'mp-30352'},
        {'name': 'AgMg', 'mp_id': 'mp-2696'},
        {'name': 'AgCa', 'mp_id': 'mp-538'},
        {'name': 'AgSr', 'mp_id': 'mp-568716'},
        {'name': 'AgBa', 'mp_id': 'mp-11840'},
        {'name': 'AgSc', 'mp_id': 'mp-11237'},
        {'name': 'AgCd', 'mp_id': 'mp-1183647'},
        {'name': 'AgHf', 'mp_id': 'mp-13156'},
        {'name': 'AgAl', 'mp_id': 'mp-1228988'},
        {'name': 'AgGa', 'mp_id': 'mp-578'},
        {'name': 'AgIn', 'mp_id': 'mp-19974'},
        {'name': 'AgCe', 'mp_id': 'mp-1206322'},
        {'name': 'IrTi', 'mp_id': 'mp-1235'},
        {'name': 'IrV', 'mp_id': 'mp-569250'},
        {'name': 'IrCr', 'mp_id': 'mp-12083'},
        {'name': 'IrMn', 'mp_id': 'mp-2728'},
        {'name': 'IrY', 'mp_id': 'mp-30746'},
        {'name': 'IrZr', 'mp_id': 'mp-30748'},
        {'name': 'IrNb', 'mp_id': 'mp-1458'},
        {'name': 'IrMo', 'mp_id': 'mp-11481'},
        {'name': 'IrLi', 'mp_id': 'mp-279'},
        {'name': 'IrBe', 'mp_id': 'mp-862714'},
        {'name': 'IrMg', 'mp_id': 'mp-568419'},
        {'name': 'IrCa', 'mp_id': 'mp-570356'},
        {'name': 'IrSr', 'mp_id': 'mp-318'},
        {'name': 'IrSc', 'mp_id': 'mp-1129'},
        {'name': 'IrCd', 'mp_id': 'mp-1199295'},
        {'name': 'IrHf', 'mp_id': 'mp-1007786'},
        {'name': 'IrTa', 'mp_id': 'mp-1187196'},
        {'name': 'IrW', 'mp_id': 'mp-30744'},
        {'name': 'IrRe', 'mp_id': 'mp-1219533'},
        {'name': 'IrAl', 'mp_id': 'mp-2294'},
        {'name': 'IrGa', 'mp_id': 'mp-11388'},
        {'name': 'IrIn', 'mp_id': 'mp-22812'},
        {'name': 'IrGe', 'mp_id': 'mp-208'},
        {'name': 'IrSn', 'mp_id': 'mp-2083'},
        {'name': 'IrSb', 'mp_id': 'mp-1247'},
        {'name': 'IrBi', 'mp_id': 'mp-1101783'},
        {'name': 'IrCe', 'mp_id': 'mp-582'},
        {'name': 'PtTi', 'mp_id': 'mp-2339'},
        {'name': 'PtV', 'mp_id': 'mp-2678'},
        {'name': 'PtCr', 'mp_id': 'mp-1206750'},
        {'name': 'PtMn', 'mp_id': 'mp-1670'},
        {'name': 'PtY', 'mp_id': 'mp-1102657'},
        {'name': 'PtZr', 'mp_id': 'mp-1065995'},
        {'name': 'PtNb', 'mp_id': 'mp-1192954'},
        {'name': 'PtMo', 'mp_id': 'mp-999502'},
        {'name': 'PtLi', 'mp_id': 'mp-2170'},
        {'name': 'PtNa', 'mp_id': 'mp-2271'},
        {'name': 'PtK', 'mp_id': 'mp-1062676'},
        {'name': 'PtCs', 'mp_id': 'mp-13548'},
        {'name': 'PtBe', 'mp_id': 'mp-1072399'},
        {'name': 'PtMg', 'mp_id': 'mp-18707'},
        {'name': 'PtCa', 'mp_id': 'mp-1103570'},
        {'name': 'PtSr', 'mp_id': 'mp-1104074'},
        {'name': 'PtBa', 'mp_id': 'mp-31498'},
        {'name': 'PtSc', 'mp_id': 'mp-892'},
        {'name': 'PtCd', 'mp_id': 'mp-1183641'},
        {'name': 'PtHf', 'mp_id': 'mp-1007691'},
        {'name': 'PtTa', 'mp_id': 'mp-30849'},
        {'name': 'PtW', 'mp_id': 'mp-1018129'},
        {'name': 'PtRe', 'mp_id': 'mp-862589'},
        {'name': 'PtAl', 'mp_id': 'mp-10904'},
        {'name': 'PtGa', 'mp_id': 'mp-1199016'},
        {'name': 'PtIn', 'mp_id': 'mp-22682'},
        {'name': 'PtGe', 'mp_id': 'mp-542640'},
        {'name': 'PtSn', 'mp_id': 'mp-19962'},
        {'name': 'PtPb', 'mp_id': 'mp-21296'},
        {'name': 'PtSb', 'mp_id': 'mp-562'},
        {'name': 'PtBi', 'mp_id': 'mp-1066078'},
        {'name': 'PtCe', 'mp_id': 'mp-21245'},
        {'name': 'AuTi', 'mp_id': 'mp-1786'},
        {'name': 'AuV', 'mp_id': 'mp-839'},
        {'name': 'AuCr', 'mp_id': 'mp-1070789'},
        {'name': 'AuMn', 'mp_id': 'mp-12674'},
        {'name': 'AuY', 'mp_id': 'mp-1066254'},
        {'name': 'AuZr', 'mp_id': 'mp-2348'},
        {'name': 'AuNb', 'mp_id': 'mp-1606'},
        {'name': 'AuLi', 'mp_id': 'mp-1206794'},
        {'name': 'AuNa', 'mp_id': 'mp-1363'},
        {'name': 'AuK', 'mp_id': 'mp-30401'},
        {'name': 'AuRb', 'mp_id': 'mp-30373'},
        {'name': 'AuCs', 'mp_id': 'mp-2667'},
        {'name': 'AuBe', 'mp_id': 'mp-30365'},
        {'name': 'AuMg', 'mp_id': 'mp-17783'},
        {'name': 'AuCa', 'mp_id': 'mp-30366'},
        {'name': 'AuSr', 'mp_id': 'mp-30420'},
        {'name': 'AuBa', 'mp_id': 'mp-570775'},
        {'name': 'AuSc', 'mp_id': 'mp-1209057'},
        {'name': 'AuCd', 'mp_id': 'mp-30370'},
        {'name': 'AuHf', 'mp_id': 'mp-1007755'},
        {'name': 'AuTa', 'mp_id': 'mp-1194495'},
        {'name': 'AuAl', 'mp_id': 'mp-2647'},
        {'name': 'AuGa', 'mp_id': 'mp-30379'},
        {'name': 'AuIn', 'mp_id': 'mp-22154'},
        {'name': 'AuSn', 'mp_id': 'mp-1775'},
        {'name': 'AuPb', 'mp_id': 'mp-22795'},
        {'name': 'AuSb', 'mp_id': 'mp-738'},
        {'name': 'AuBi', 'mp_id': 'mp-570113'},
        {'name': 'AuCe', 'mp_id': 'mp-1025468'},
        {'name': 'TiMn', 'mp_id': 'mp-1949'},
        {'name': 'TiMo', 'mp_id': 'mp-1017983'},
        {'name': 'TiBe', 'mp_id': 'mp-2749'},
        {'name': 'TiCd', 'mp_id': 'mp-30500'},
        {'name': 'TiRe', 'mp_id': 'mp-2179'},
        {'name': 'TiOs', 'mp_id': 'mp-865899'},
        {'name': 'TiAl', 'mp_id': 'mp-1953'},
        {'name': 'TiGa', 'mp_id': 'mp-2767'},
        {'name': 'TiIn', 'mp_id': 'mp-1216825'},
        {'name': 'TiGe', 'mp_id': 'mp-568151'},
        {'name': 'TiSn', 'mp_id': 'mp-30875'},
        {'name': 'TiPb', 'mp_id': 'mp-866184'},
        {'name': 'TiSb', 'mp_id': 'mp-1206780'},
        {'name': 'TiBi', 'mp_id': 'mp-568069'},
        {'name': 'VMn', 'mp_id': 'mp-316'},
        {'name': 'VMo', 'mp_id': 'mp-1216323'},
        {'name': 'VBe', 'mp_id': 'mp-11281'},
        {'name': 'VTa', 'mp_id': 'mp-567276'},
        {'name': 'VW', 'mp_id': 'mp-1216231'},
        {'name': 'VRe', 'mp_id': 'mp-1216229'},
        {'name': 'VOs', 'mp_id': 'mp-12778'},
        {'name': 'VAl', 'mp_id': 'mp-1228001'},
        {'name': 'VGa', 'mp_id': 'mp-22568'},
        {'name': 'VGe', 'mp_id': 'mp-1221'},
        {'name': 'VSn', 'mp_id': 'mp-21342'},
        {'name': 'VSb', 'mp_id': 'mp-1555'},
        {'name': 'CrBe', 'mp_id': 'mp-30438'},
        {'name': 'CrAl', 'mp_id': 'mp-867780'},
        {'name': 'CrGa', 'mp_id': 'mp-1070544'},
        {'name': 'CrSb', 'mp_id': 'mp-22498'},
        {'name': 'MnZr', 'mp_id': 'mp-2116'},
        {'name': 'MnNb', 'mp_id': 'mp-12659'},
        {'name': 'MnBe', 'mp_id': 'mp-11270'},
        {'name': 'MnSc', 'mp_id': 'mp-2039'},
        {'name': 'MnHf', 'mp_id': 'mp-11449'},
        {'name': 'MnTa', 'mp_id': 'mp-12678'},
        {'name': 'MnAl', 'mp_id': 'mp-771'},
        {'name': 'MnGa', 'mp_id': 'mp-1001836'},
        {'name': 'MnGe', 'mp_id': 'mp-1078464'},
        {'name': 'MnSb', 'mp_id': 'mp-786'},
        {'name': 'YBe', 'mp_id': 'mp-1193534'},
        {'name': 'YMg', 'mp_id': 'mp-615'},
        {'name': 'YCd', 'mp_id': 'mp-915'},
        {'name': 'YRe', 'mp_id': 'mp-570923'},
        {'name': 'YOs', 'mp_id': 'mp-1188757'},
        {'name': 'YAl', 'mp_id': 'mp-11228'},
        {'name': 'YGa', 'mp_id': 'mp-865598'},
        {'name': 'YIn', 'mp_id': 'mp-21294'},
        {'name': 'YGe', 'mp_id': 'mp-9971'},
        {'name': 'YSn', 'mp_id': 'mp-13010'},
        {'name': 'YPb', 'mp_id': 'mp-636614'},
        {'name': 'YSb', 'mp_id': 'mp-215'},
        {'name': 'YBi', 'mp_id': 'mp-23241'},
        {'name': 'ZrMo', 'mp_id': 'mp-2049'},
        {'name': 'ZrBe', 'mp_id': 'mp-11283'},
        {'name': 'ZrSc', 'mp_id': 'mp-1188062'},
        {'name': 'ZrCd', 'mp_id': 'mp-1017540'},
        {'name': 'ZrW', 'mp_id': 'mp-675'},
        {'name': 'ZrRe', 'mp_id': 'mp-12109'},
        {'name': 'ZrOs', 'mp_id': 'mp-11541'},
        {'name': 'ZrAl', 'mp_id': 'mp-2772'},
        {'name': 'ZrGa', 'mp_id': 'mp-30682'},
        {'name': 'ZrIn', 'mp_id': 'mp-570578'},
        {'name': 'ZrGe', 'mp_id': 'mp-2430'},
        {'name': 'ZrSn', 'mp_id': 'mp-755328'},
        {'name': 'ZrPb', 'mp_id': 'mp-681992'},
        {'name': 'ZrSb', 'mp_id': 'mp-10638'},
        {'name': 'ZrBi', 'mp_id': 'mp-30933'},
        {'name': 'NbMo', 'mp_id': 'mp-1220327'},
        {'name': 'NbBe', 'mp_id': 'mp-11272'},
        {'name': 'NbW', 'mp_id': 'mp-1220316'},
        {'name': 'NbRe', 'mp_id': 'mp-1220322'},
        {'name': 'NbOs', 'mp_id': 'mp-1932'},
        {'name': 'NbAl', 'mp_id': 'mp-1842'},
        {'name': 'NbGa', 'mp_id': 'mp-11393'},
        {'name': 'NbIn', 'mp_id': 'mp-22060'},
        {'name': 'NbGe', 'mp_id': 'mp-363'},
        {'name': 'NbSn', 'mp_id': 'mp-1046'},
        {'name': 'NbSb', 'mp_id': 'mp-1969'},
        {'name': 'MoBe', 'mp_id': 'mp-1677'},
        {'name': 'MoHf', 'mp_id': 'mp-2363'},
        {'name': 'MoTa', 'mp_id': 'mp-1217895'},
        {'name': 'MoW', 'mp_id': 'mp-1221387'},
        {'name': 'MoRe', 'mp_id': 'mp-12662'},
        {'name': 'MoAl', 'mp_id': 'mp-568607'},
        {'name': 'MoGa', 'mp_id': 'mp-2377'},
        {'name': 'MoGe', 'mp_id': 'mp-13688'},
        {'name': 'LiMg', 'mp_id': 'mp-1185380'},
        {'name': 'LiCa', 'mp_id': 'mp-570466'},
        {'name': 'LiSr', 'mp_id': 'mp-1195042'},
        {'name': 'LiBa', 'mp_id': 'mp-210'},
        {'name': 'LiCd', 'mp_id': 'mp-975904'},
        {'name': 'LiAl', 'mp_id': 'mp-1210753'},
        {'name': 'LiGa', 'mp_id': 'mp-29210'},
        {'name': 'LiIn', 'mp_id': 'mp-31324'},
        {'name': 'LiGe', 'mp_id': 'mp-9918'},
        {'name': 'LiSn', 'mp_id': 'mp-1185265'},
        {'name': 'LiPb', 'mp_id': 'mp-2314'},
        {'name': 'LiSb', 'mp_id': 'mp-7955'},
        {'name': 'LiBi', 'mp_id': 'mp-22902'},
        {'name': 'NaBa', 'mp_id': 'mp-1247744'},
        {'name': 'NaCd', 'mp_id': 'mp-1186024'},
        {'name': 'NaGa', 'mp_id': 'mp-454'},
        {'name': 'NaIn', 'mp_id': 'mp-20628'},
        {'name': 'NaGe', 'mp_id': 'mp-29657'},
        {'name': 'NaSn', 'mp_id': 'mp-11051'},
        {'name': 'NaPb', 'mp_id': 'mp-30792'},
        {'name': 'NaSb', 'mp_id': 'mp-7944'},
        {'name': 'NaBi', 'mp_id': 'mp-22924'},
        {'name': 'KCs', 'mp_id': 'mp-1183940'},
        {'name': 'KCd', 'mp_id': 'mp-397'},
        {'name': 'KGa', 'mp_id': 'mp-181'},
        {'name': 'KIn', 'mp_id': 'mp-22481'},
        {'name': 'KGe', 'mp_id': 'mp-2146'},
        {'name': 'KSn', 'mp_id': 'mp-542374'},
        {'name': 'KPb', 'mp_id': 'mp-21526'},
        {'name': 'KSb', 'mp_id': 'mp-1536'},
        {'name': 'KBi', 'mp_id': 'mp-31286'},
        {'name': 'RbCd', 'mp_id': 'mp-1040'},
        {'name': 'RbGa', 'mp_id': 'mp-31493'},
        {'name': 'RbIn', 'mp_id': 'mp-21477'},
        {'name': 'RbGe', 'mp_id': 'mp-1888'},
        {'name': 'RbSn', 'mp_id': 'mp-11054'},
        {'name': 'RbPb', 'mp_id': 'mp-21525'},
        {'name': 'RbSb', 'mp_id': 'mp-10487'},
        {'name': 'RbBi', 'mp_id': 'mp-23253'},
        {'name': 'CsCd', 'mp_id': 'mp-1713'},
        {'name': 'CsGa', 'mp_id': 'mp-574338'},
        {'name': 'CsIn', 'mp_id': 'mp-542339'},
        {'name': 'CsGe', 'mp_id': 'mp-1273'},
        {'name': 'CsSn', 'mp_id': 'mp-571056'},
        {'name': 'CsPb', 'mp_id': 'mp-574070'},
        {'name': 'CsSb', 'mp_id': 'mp-573514'},
        {'name': 'CsBi', 'mp_id': 'mp-23163'},
        {'name': 'BeCa', 'mp_id': 'mp-1845'},
        {'name': 'BeSr', 'mp_id': 'mp-2080'},
        {'name': 'BeSc', 'mp_id': 'mp-11277'},
        {'name': 'BeHf', 'mp_id': 'mp-2025'},
        {'name': 'BeTa', 'mp_id': 'mp-11278'},
        {'name': 'BeW', 'mp_id': 'mp-11282'},
        {'name': 'BeRe', 'mp_id': 'mp-11275'},
        {'name': 'BeOs', 'mp_id': 'mp-1199166'},
        {'name': 'BeCe', 'mp_id': 'mp-457'},
        {'name': 'MgCa', 'mp_id': 'mp-2432'},
        {'name': 'MgSr', 'mp_id': 'mp-2572'},
        {'name': 'MgBa', 'mp_id': 'mp-1183308'},
        {'name': 'MgSc', 'mp_id': 'mp-1185790'},
        {'name': 'MgCd', 'mp_id': 'mp-11307'},
        {'name': 'MgAl', 'mp_id': 'mp-1094116'},
        {'name': 'MgGa', 'mp_id': 'mp-30650'},
        {'name': 'MgIn', 'mp_id': 'mp-2313'},
        {'name': 'MgGe', 'mp_id': 'mp-408'},
        {'name': 'MgSn', 'mp_id': 'mp-2343'},
        {'name': 'MgPb', 'mp_id': 'mp-20724'},
        {'name': 'MgSb', 'mp_id': 'mp-1196139'},
        {'name': 'MgBi', 'mp_id': 'mp-569018'},
        {'name': 'MgCe', 'mp_id': 'mp-1103919'},
        {'name': 'CaCd', 'mp_id': 'mp-1073'},
        {'name': 'CaAl', 'mp_id': 'mp-2404'},
        {'name': 'CaGa', 'mp_id': 'mp-6914'},
        {'name': 'CaIn', 'mp_id': 'mp-21187'},
        {'name': 'CaGe', 'mp_id': 'mp-2360'},
        {'name': 'CaSn', 'mp_id': 'mp-22735'},
        {'name': 'CaPb', 'mp_id': 'mp-30478'},
        {'name': 'CaSb', 'mp_id': 'mp-9925'},
        {'name': 'CaBi', 'mp_id': 'mp-569535'},
        {'name': 'SrBa', 'mp_id': 'mp-1227650'},
        {'name': 'SrCd', 'mp_id': 'mp-30496'},
        {'name': 'SrAl', 'mp_id': 'mp-22318'},
        {'name': 'SrGa', 'mp_id': 'mp-182'},
        {'name': 'SrIn', 'mp_id': 'mp-608072'},
        {'name': 'SrGe', 'mp_id': 'mp-2576'},
        {'name': 'SrSn', 'mp_id': 'mp-978'},
        {'name': 'SrPb', 'mp_id': 'mp-21093'},
        {'name': 'SrSb', 'mp_id': 'mp-10636'},
        {'name': 'SrBi', 'mp_id': 'mp-30893'},
        {'name': 'BaCd', 'mp_id': 'mp-527'},
        {'name': 'BaAl', 'mp_id': 'mp-1903'},
        {'name': 'BaGa', 'mp_id': 'mp-1219'},
        {'name': 'BaIn', 'mp_id': 'mp-31509'},
        {'name': 'BaGe', 'mp_id': 'mp-13922'},
        {'name': 'BaSn', 'mp_id': 'mp-1981'},
        {'name': 'BaPb', 'mp_id': 'mp-21246'},
        {'name': 'BaSb', 'mp_id': 'mp-624668'},
        {'name': 'BaBi', 'mp_id': 'mp-569529'},
        {'name': 'ScCd', 'mp_id': 'mp-1211'},
        {'name': 'ScHf', 'mp_id': 'mp-976128'},
        {'name': 'ScRe', 'mp_id': 'mp-11557'},
        {'name': 'ScOs', 'mp_id': 'mp-567612'},
        {'name': 'ScAl', 'mp_id': 'mp-2121'},
        {'name': 'ScGa', 'mp_id': 'mp-932'},
        {'name': 'ScIn', 'mp_id': 'mp-1207100'},
        {'name': 'ScGe', 'mp_id': 'mp-9970'},
        {'name': 'ScSn', 'mp_id': 'mp-2398'},
        {'name': 'ScPb', 'mp_id': 'mp-510209'},
        {'name': 'ScSb', 'mp_id': 'mp-549'},
        {'name': 'ScBi', 'mp_id': 'mp-570632'},
        {'name': 'CdHf', 'mp_id': 'mp-1007758'},
        {'name': 'CdSb', 'mp_id': 'mp-1321'},
        {'name': 'CdCe', 'mp_id': 'mp-866189'},
        {'name': 'HfW', 'mp_id': 'mp-1400'},
        {'name': 'HfRe', 'mp_id': 'mp-1689'},
        {'name': 'HfOs', 'mp_id': 'mp-11452'},
        {'name': 'HfAl', 'mp_id': 'mp-568718'},
        {'name': 'HfGa', 'mp_id': 'mp-11440'},
        {'name': 'HfIn', 'mp_id': 'mp-22050'},
        {'name': 'HfGe', 'mp_id': 'mp-13683'},
        {'name': 'HfSn', 'mp_id': 'mp-510691'},
        {'name': 'HfPb', 'mp_id': 'mp-1184772'},
        {'name': 'HfSb', 'mp_id': 'mp-13450'},
        {'name': 'HfBi', 'mp_id': 'mp-1192314'},
        {'name': 'TaW', 'mp_id': 'mp-979289'},
        {'name': 'TaRe', 'mp_id': 'mp-1187203'},
        {'name': 'TaOs', 'mp_id': 'mp-1187197'},
        {'name': 'TaAl', 'mp_id': 'mp-869'},
        {'name': 'TaGa', 'mp_id': 'mp-11416'},
        {'name': 'TaGe', 'mp_id': 'mp-639805'},
        {'name': 'TaSn', 'mp_id': 'mp-30871'},
        {'name': 'TaSb', 'mp_id': 'mp-11697'},
        {'name': 'WOs', 'mp_id': 'mp-1186374'},
        {'name': 'WAl', 'mp_id': 'mp-30337'},
        {'name': 'ReOs', 'mp_id': 'mp-1219509'},
        {'name': 'ReAl', 'mp_id': 'mp-1648'},
        {'name': 'ReGa', 'mp_id': 'mp-1188393'},
        {'name': 'OsAl', 'mp_id': 'mp-7188'},
        {'name': 'OsGa', 'mp_id': 'mp-570844'},
        {'name': 'OsGe', 'mp_id': 'mp-10032'},
        {'name': 'OsSb', 'mp_id': 'mp-2695'},
        {'name': 'OsCe', 'mp_id': 'mp-1188974'},
        {'name': 'AlSb', 'mp_id': 'mp-2624'},
        {'name': 'AlCe', 'mp_id': 'mp-567305'},
        {'name': 'GaSb', 'mp_id': 'mp-1156'},
        {'name': 'GaCe', 'mp_id': 'mp-862696'},
        {'name': 'InSb', 'mp_id': 'mp-20012'},
        {'name': 'InBi', 'mp_id': 'mp-1001833'},
        {'name': 'InCe', 'mp_id': 'mp-20369'},
        {'name': 'GeCe', 'mp_id': 'mp-1079395'},
        {'name': 'SnCe', 'mp_id': 'mp-1911'},
        {'name': 'PbCe', 'mp_id': 'mp-570018'},
        {'name': 'SbBi', 'mp_id': 'mp-1227290'},
        {'name': 'SbCe', 'mp_id': 'mp-387'},
        {'name': 'BiCe', 'mp_id': 'mp-23285'},
        ]
type4=[
        {"name": "Fe", "mp_id": "mp-150"},
{"name": "Fe", "mp_id": "mp-136"},
{"name": "Fe", "mp_id": "mp-13"},
{"name": "Co", "mp_id": "mp-1072089"},
{"name": "Co", "mp_id": "mp-669382"},
{"name": "Co", "mp_id": "mp-54"},
{"name": "Co", "mp_id": "mp-102"},
{"name": "Ni", "mp_id": "mp-10257"},
{"name": "Ni", "mp_id": "mp-23"},
{"name": "Cu", "mp_id": "mp-30"},
{"name": "Zn", "mp_id": "mp-79"},
{"name": "Ru", "mp_id": "mp-33"},
{"name": "Rh", "mp_id": "mp-74"},
{"name": "Pd", "mp_id": "mp-2"},
{"name": "Ag", "mp_id": "mp-8566"},
{"name": "Ag", "mp_id": "mp-124"},
{"name": "Ag", "mp_id": "mp-10597"},
{"name": "Ir", "mp_id": "mp-101"},
{"name": "Pt", "mp_id": "mp-126"},
{"name": "Au", "mp_id": "mp-81"},
{"name": "Ti", "mp_id": "mp-46"},
{"name": "Ti", "mp_id": "mp-72"},
{"name": "Ti", "mp_id": "mp-73"},
{"name": "V", "mp_id": "mp-146"},
{"name": "Cr", "mp_id": "mp-90"},
{"name": "Mn", "mp_id": "mp-35"},
{"name": "Mn", "mp_id": "mp-542909"},
{"name": "Y", "mp_id": "mp-9"},
{"name": "Y", "mp_id": "mp-112"},
{"name": "Zr", "mp_id": "mp-41"},
{"name": "Zr", "mp_id": "mp-131"},
{"name": "Nb", "mp_id": "mp-75"},
{"name": "Mo", "mp_id": "mp-129"},
{"name": "Li", "mp_id": "mp-135"},
{"name": "Li", "mp_id": "mp-51"},
{"name": "Li", "mp_id": "mp-10173"},
{"name": "Li", "mp_id": "mp-567337"},
{"name": "Li", "mp_id": "mp-1018134"},
{"name": "Na", "mp_id": "mp-973198"},
{"name": "Na", "mp_id": "mp-567772"},
{"name": "Na", "mp_id": "mp-127"},
{"name": "Na", "mp_id": "mp-1079952"},
{"name": "Na", "mp_id": "mp-10172"},
{"name": "K", "mp_id": "mp-1080043"},
{"name": "K", "mp_id": "mp-1068966"},
{"name": "K", "mp_id": "mp-1078640"},
{"name": "K", "mp_id": "mp-10157"},
{"name": "K", "mp_id": "mp-1199937"},
{"name": "K", "mp_id": "mp-58"},
{"name": "Rb", "mp_id": "mp-70"},
{"name": "Rb", "mp_id": "mp-639736"},
{"name": "Rb", "mp_id": "mp-569688"},
{"name": "Rb", "mp_id": "mp-639755"},
{"name": "Rb", "mp_id": "mp-1018045"},
{"name": "Rb", "mp_id": "mp-1063817"},
{"name": "Cs", "mp_id": "mp-1182809"},
{"name": "Cs", "mp_id": "mp-1007976"},
{"name": "Cs", "mp_id": "mp-573579"},
{"name": "Cs", "mp_id": "mp-1012110"},
{"name": "Cs", "mp_id": "mp-3"},
{"name": "Cs", "mp_id": "mp-11832"},
{"name": "Cs", "mp_id": "mp-1"},
{"name": "Cs", "mp_id": "mp-1096915"},
{"name": "Cs", "mp_id": "mp-672241"},
{"name": "Cs", "mp_id": "mp-1055940"},
{"name": "Cs", "mp_id": "mp-639727"},
{"name": "Be", "mp_id": "mp-20"},
{"name": "Be", "mp_id": "mp-87"},
{"name": "Mg", "mp_id": "mp-110"},
{"name": "Mg", "mp_id": "mp-153"},
{"name": "Mg", "mp_id": "mp-1056351"},
{"name": "Ca", "mp_id": "mp-21"},
{"name": "Ca", "mp_id": "mp-1067285"},
{"name": "Ca", "mp_id": "mp-1078638"},
{"name": "Ca", "mp_id": "mp-132"},
{"name": "Ca", "mp_id": "mp-45"},
{"name": "Sr", "mp_id": "mp-76"},
{"name": "Sr", "mp_id": "mp-567826"},
{"name": "Sr", "mp_id": "mp-95"},
{"name": "Sr", "mp_id": "mp-10617"},
{"name": "Sr", "mp_id": "mp-139"},
{"name": "Sr", "mp_id": "mp-19858"},
{"name": "Ba", "mp_id": "mp-122"},
{"name": "Ba", "mp_id": "mp-570384"},
{"name": "Ba", "mp_id": "mp-1058581"},
{"name": "Ba", "mp_id": "mp-10679"},
{"name": "Ba", "mp_id": "mp-56"},
{"name": "Sc", "mp_id": "mp-1056366"},
{"name": "Sc", "mp_id": "mp-1064244"},
{"name": "Sc", "mp_id": "mp-567308"},
{"name": "Sc", "mp_id": "mp-36"},
{"name": "Sc", "mp_id": "mp-67"},
{"name": "Cd", "mp_id": "mp-94"},
{"name": "Hf", "mp_id": "mp-100"},
{"name": "Hf", "mp_id": "mp-103"},
{"name": "Ta", "mp_id": "mp-569794"},
{"name": "Ta", "mp_id": "mp-42"},
{"name": "Ta", "mp_id": "mp-6986"},
{"name": "Ta", "mp_id": "mp-50"},
{"name": "W", "mp_id": "mp-91"},
{"name": "Re", "mp_id": "mp-8"},
{"name": "Os", "mp_id": "mp-1080694"},
{"name": "Os", "mp_id": "mp-49"},
{"name": "Al", "mp_id": "mp-134"},
{"name": "Al", "mp_id": "mp-998860"},
{"name": "Ga", "mp_id": "mp-569007"},
{"name": "Ga", "mp_id": "mp-140"},
{"name": "Ga", "mp_id": "mp-142"},
{"name": "Ga", "mp_id": "mp-569423"},
{"name": "Ga", "mp_id": "mp-10021"},
{"name": "Ga", "mp_id": "mp-567540"},
{"name": "In", "mp_id": "mp-1055994"},
{"name": "In", "mp_id": "mp-85"},
{"name": "Ge", "mp_id": "mp-137"},
{"name": "Ge", "mp_id": "mp-1091415"},
{"name": "Ge", "mp_id": "mp-32"},
{"name": "Ge", "mp_id": "mp-78"},
{"name": "Ge", "mp_id": "mp-1198022"},
{"name": "Ge", "mp_id": "mp-1080106"},
{"name": "Ge", "mp_id": "mp-1061054"},
{"name": "Ge", "mp_id": "mp-128"},
{"name": "Ge", "mp_id": "mp-1007760"},
{"name": "Sn", "mp_id": "mp-623511"},
{"name": "Sn", "mp_id": "mp-117"},
{"name": "Sn", "mp_id": "mp-84"},
{"name": "Sn", "mp_id": "mp-55"},
{"name": "Sn", "mp_id": "mp-7162"},
{"name": "Pb", "mp_id": "mp-20483"},
{"name": "Pb", "mp_id": "mp-20745"},
{"name": "Pb", "mp_id": "mp-1057273"},
{"name": "Pb", "mp_id": "mp-22692"},
{"name": "Sb", "mp_id": "mp-104"},
{"name": "Sb", "mp_id": "mp-7761"},
{"name": "Sb", "mp_id": "mp-1236935"},
{"name": "Sb", "mp_id": "mp-567409"},
{"name": "Sb", "mp_id": "mp-133"},
{"name": "Sb", "mp_id": "mp-567144"},
{"name": "Sb", "mp_id": "mp-80"},
{"name": "Bi", "mp_id": "mp-568610"},
{"name": "Bi", "mp_id": "mp-1067758"},
{"name": "Bi", "mp_id": "mp-23157"},
{"name": "Bi", "mp_id": "mp-568087"},
{"name": "Bi", "mp_id": "mp-567379"},
{"name": "Bi", "mp_id": "mp-567597"},
{"name": "Bi", "mp_id": "mp-1182070"},
{"name": "Bi", "mp_id": "mp-1078637"},
{"name": "Ce", "mp_id": "mp-20736"},
{"name": "Ce", "mp_id": "mp-10024"},
{"name": "Ce", "mp_id": "mp-567332"},
{"name": "Ce", "mp_id": "mp-20372"},
{"name": "Ce", "mp_id": "mp-64"},
{"name": "Ce", "mp_id": "mp-28"}
]
